export const data = {
  content: {
    measures: {
      lg: {
        table: {
          height: "80%",
          width: "90%",
        },
      },
    },
    colors: {
      byGroupType: {
        "alkali metal": "#f5f534",
        "alkaline earth metal": "#a1d344",
        metal: "#7b5ba8",
        metalloid: "#70cbeb",
        nonmetal: "#f1b200",
        halogen: "#28a87b",
        "noble gas": "#e86262",
        "transition metal": "#a2c7d3",
        "post-transition metal": "#f8de85",
      },
    },
  },
  elementsData: {
    groupBlocks: {
      "Alkali Metal": {
        id: "1A",
        elements: [1, 3, 11, 19, 37, 55, 87],
        rows: 7,
        columns: 1,
        gridArea: "AKM",
        color: "#fff",
      },
      "Alkaline Earth Metals": {
        id: "2A",
        elements: [4, 12, 20, 38, 56, 88],
        rows: 7,
        columns: 1,
        gridArea: "AKEM",
        color: "#fff",
      },
      "Transition Metals 1B": {
        id: "TM1B",
        elements: [21, 39, -1, -2],
        rows: 7,
        columns: 1,
        gridArea: "TM1B",
        color: "#fff",
      },
      "Transition Metals 2B": {
        id: "TM2B",
        elements: [22, 40, 72, 104],
        rows: 7,
        columns: 1,
        gridArea: "TM2B",
        color: "#fff",
      },
      "Transition Metals 3B": {
        id: "TM3B",
        elements: [23, 41, 73, 105],
        rows: 7,
        columns: 1,
        gridArea: "TM3B",
        color: "#fff",
      },
      "Transition Metals 4B": {
        id: "TM4B",
        elements: [24, 42, 74, 106],
        rows: 7,
        columns: 1,
        gridArea: "TM4B",
        color: "#fff",
      },
      "Transition Metals 5B": {
        id: "TM5B",
        elements: [25, 43, 75, 107],
        rows: 7,
        columns: 1,
        gridArea: "TM5B",
        color: "#fff",
      },
      "Transition Metals 6B": {
        id: "TM6B",
        elements: [26, 44, 76, 108],
        rows: 7,
        columns: 1,
        gridArea: "TM6B",
        color: "#fff",
      },
      "Transition Metals 7B": {
        id: "TM7B",
        elements: [27, 45, 77, 109],
        rows: 7,
        columns: 1,
        gridArea: "TM7B",
        color: "#fff",
      },
      "Transition Metals 8.1B": {
        id: "TM8.1B",
        elements: [28, 46, 78, 110],
        rows: 7,
        columns: 1,
        gridArea: "TM8.1B",
        color: "#fff",
      },
      "Transition Metals 8.2B": {
        id: "TM8.2B",
        elements: [29, 47, 79, 111],
        rows: 7,
        columns: 1,
        gridArea: "TM8.2B",
        color: "#fff",
      },
      "Transition Metals 8.3B": {
        id: "TM8.3B",
        elements: [30, 48, 80, 112],
        rows: 7,
        columns: 1,
        gridArea: "TM8.3B",
        color: "#fff",
      },
      "Borum Group": {
        id: "3A",
        elements: [5, 13, 31, 49, 81, 113],
        rows: 7,
        columns: 1,
        gridArea: "BG",
        color: "#fff",
      },
      "Carbon Group": {
        id: "4A",
        elements: [6, 14, 32, 50, 82, 114],
        rows: 7,
        columns: 1,
        gridArea: "CG",
        color: "#fff",
      },
      "Nitrogen Group": {
        id: "5A",
        elements: [7, 15, 33, 51, 83, 115],
        rows: 7,
        columns: 1,
        gridArea: "NG",
        color: "#fff",
      },
      Chalcogens: {
        id: "6A",
        elements: [8, 16, 34, 52, 84, 116],
        rows: 7,
        columns: 1,
        gridArea: "CAL",
        color: "#fff",
      },

      Halogens: {
        id: "7A",
        elements: [9, 17, 35, 53, 85, 117],
        rows: 7,
        columns: 1,
        gridArea: "HAL",
        color: "#fff",
      },

      "Noble Gases": {
        id: "8A",
        elements: [2, 10, 18, 36, 54, 86, 118],
        rows: 7,
        columns: 1,
        gridArea: "NGas",
        color: "#fff",
      },

      // TODO Lan & Act
      //   Lanthanides: {
      //     id: "7A",
      //     elements: [2, 10, 18, 36, 54, 86, 118],
      //     rows: 7,
      //     columns: 1,
      //     gridArea: "HAL",
      //     color: "#fff",
      //   },

      //   Actinides: {
      //     id: "7A",
      //     elements: [2, 10, 18, 36, 54, 86, 118],
      //     rows: 7,
      //     columns: 1,
      //     gridArea: "HAL",
      //     color: "#fff",
      //   },
    },
  },
};
